//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCR.AsignacionAutomaticaCargas.Interfaz.View.Franja_Horaria {
    
    
    public partial class Consultar_Franja_Horaria {
        
        /// <summary>
        /// dgFranjaHoraria control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DataGrid dgFranjaHoraria;
    }
}
